name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  SOLUTION_PATH: src/RepoDb.Adapter.MariaDb/RepoDb.Adapter.MariaDb.slnx
  REPODB_MARIADB_CONSTR_SYSTEM: "Server=127.0.0.1;Port=3307;Database=sys;User ID=root;Password=RepoDB2026;"
  REPODB_MARIADB_CONSTR: "Server=127.0.0.1;Port=3307;Database=RepoDb.Adapter.MariaDb;User ID=root;Password=RepoDB2026;AllowLoadLocalInfile=True;AllowUserVariables=True;"

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: RepoDB2026
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mariadb-admin ping -uroot -pRepoDB2026"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore $SOLUTION_PATH

      - name: Build
        run: dotnet build $SOLUTION_PATH --no-restore

      - name: Test
        run: dotnet test $SOLUTION_PATH --no-build --logger "console;verbosity=normal"
